# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-10 12:50
from __future__ import unicode_literals

from django.db import migrations, models
import jiahuaApp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BatchHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insertTime', models.DateTimeField(auto_now=True, verbose_name='\u5bfc\u5165\u65e5\u671f')),
                ('insertFileName', models.CharField(max_length=20, verbose_name='\u5bfc\u5165\u6587\u4ef6\u540d')),
                ('insertResult', models.CharField(max_length=20, verbose_name='\u5bfc\u5165\u7ed3\u679c')),
                ('insertNum', models.CharField(max_length=20, verbose_name='\u5bfc\u5165\u8ba2\u5355\u603b\u6570')),
                ('uploadFile', models.FileField(upload_to='upload', verbose_name='\u6587\u4ef6\u8def\u5f84')),
            ],
        ),
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plateNum', models.CharField(max_length=20, verbose_name='\u8f66\u724c\u53f7')),
                ('catType', models.CharField(max_length=20, verbose_name='\u8f66\u578b')),
                ('fullName', models.CharField(blank=True, max_length=20, verbose_name='\u59d3\u540d')),
                ('phoneNumber', models.CharField(blank=True, max_length=20, verbose_name='\u7535\u8bdd')),
                ('catOther', models.CharField(max_length=45, verbose_name='\u8f66\u51b5\u5907\u6ce8')),
                ('ofterPlace', models.CharField(blank=True, max_length=60, verbose_name='\u5e38\u8fd0\u5730\u70b9')),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(blank=True, max_length=200, verbose_name='\u5185\u5bb9')),
                ('action', models.CharField(blank=True, max_length=10, verbose_name='\u52a8\u4f5c')),
                ('operator', models.CharField(blank=True, max_length=10, verbose_name='\u64cd\u4f5c\u5458')),
                ('operateTime', models.DateField(auto_now_add=True, verbose_name='\u64cd\u4f5c\u65f6\u95f4')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='\u59d3\u540d')),
                ('username', models.CharField(blank=True, max_length=200, verbose_name='\u7528\u6237\u540d')),
                ('latitude', models.CharField(blank=True, max_length=200, verbose_name='\u7eac\u5ea6')),
                ('longitude', models.CharField(blank=True, max_length=10, verbose_name='\u7ecf\u5ea6')),
                ('precision', models.CharField(blank=True, max_length=10, verbose_name='\u7cbe\u786e\u5ea6')),
                ('insertTime', models.DateTimeField(auto_now_add=True, verbose_name='\u4e0a\u62a5\u65f6\u95f4')),
            ],
        ),
        migrations.CreateModel(
            name='OrderForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catNum', models.IntegerField(blank=True, null=True, verbose_name='\u8f66\u6b21')),
                ('tranNum', models.IntegerField(blank=True, null=True, verbose_name='\u8d9f\u6570')),
                ('placeNum', models.IntegerField(blank=True, null=True, verbose_name='\u4efb\u52a1\u6e05\u5355\u6570')),
                ('getGoodsDate', models.DateField(blank=True, null=True, verbose_name='\u53d6\u8d27\u65e5\u671f')),
                ('getGoodsTime', models.TimeField(blank=True, null=True, verbose_name='\u8282\u70b9\u65f6\u95f4')),
                ('sendName', models.CharField(max_length=20, verbose_name='\u53d1\u8d27\u65b9\u59d3\u540d')),
                ('sendPhoneNumber', models.CharField(blank=True, max_length=20, verbose_name='\u53d1\u8d27\u65b9\u7535\u8bdd')),
                ('sendAddress', models.CharField(blank=True, max_length=20, verbose_name='\u53d1\u8d27\u65b9\u5730\u5740')),
                ('sendCode', models.CharField(blank=True, max_length=20, verbose_name='\u51fa\u8d27\u5730\u5b8c\u6574\u7801')),
                ('receiveName', models.CharField(max_length=20, verbose_name='\u6536\u8d27\u65b9\u59d3\u540d')),
                ('receivePhoneNumber', models.CharField(blank=True, max_length=20, verbose_name='\u6536\u8d27\u65b9\u7535\u8bdd')),
                ('receiveAddress', models.CharField(blank=True, max_length=20, verbose_name='\u6536\u8d27\u65b9\u5730\u5740')),
                ('receiveCode', models.CharField(blank=True, max_length=20, verbose_name='\u4ea4\u8d27\u5730\u7f16\u7801')),
                ('fe', models.IntegerField(blank=True, default=0, verbose_name='\u94c1\u67b6')),
                ('box', models.IntegerField(blank=True, default=0, verbose_name='\u80f6\u7bb1')),
                ('lastDate', models.DateField(blank=True, null=True, verbose_name='\u7eb3\u671f')),
                ('lastTime', models.TimeField(blank=True, null=True, verbose_name='\u7eb3\u65f6')),
                ('runType', models.CharField(max_length=20, null=True, verbose_name='\u8fd0\u4f5c\u65b9\u5f0f')),
                ('plateNum', models.CharField(blank=True, max_length=20, null=True, verbose_name='\u8f66\u53f7')),
                ('createTime', models.DateField(db_index=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('receiveFormTime', models.DateTimeField(blank=True, null=True, verbose_name='\u63a5\u5355\u65f6\u95f4')),
                ('receiveFormPerson', models.CharField(blank=True, max_length=20, verbose_name='\u63a5\u5355\u4eba')),
                ('receiveGoodsTime', models.DateTimeField(blank=True, null=True, verbose_name='\u88c5\u8d27\u65f6\u95f4')),
                ('receiveGoodsPerson', models.CharField(blank=True, max_length=20, verbose_name='\u88c5\u8d27\u4eba')),
                ('acceptTime', models.DateTimeField(blank=True, null=True, verbose_name='\u7b7e\u6536\u65f6\u95f4')),
                ('acceptPerson', models.CharField(blank=True, max_length=20, verbose_name='\u7b7e\u6536\u4eba')),
                ('problem', models.IntegerField(default=0, verbose_name='\u5f02\u5e38')),
                ('other', models.CharField(blank=True, max_length=20, verbose_name='\u5907\u6ce8')),
                ('stateType', models.IntegerField(default=0, verbose_name='\u8fd0\u5355\u72b6\u6001')),
                ('getStartTime', models.DateTimeField(blank=True, null=True, verbose_name='\u53d6\u8d27\u5f00\u59cb\u65f6\u95f4')),
                ('getEndTime', models.DateTimeField(blank=True, null=True, verbose_name='\u53d6\u8d27\u7ed3\u675f\u65f6\u95f4')),
                ('getTime', models.IntegerField(blank=True, null=True, verbose_name='\u53d6\u8d27\u65f6\u957f')),
                ('sendStartTime', models.DateTimeField(blank=True, null=True, verbose_name='\u6536\u8d27\u5f00\u59cb\u65f6\u95f4')),
                ('sendEndTime', models.DateTimeField(blank=True, null=True, verbose_name='\u6536\u8d27\u7ed3\u675f\u65f6\u95f4')),
                ('sendTime', models.IntegerField(blank=True, null=True, verbose_name='\u6536\u8d27\u65f6\u957f')),
                ('operator', models.CharField(blank=True, max_length=20, verbose_name='\u64cd\u4f5c\u5458')),
            ],
            bases=(models.Model, jiahuaApp.models.BaseModel),
        ),
        migrations.CreateModel(
            name='ReceiveClient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='\u59d3\u540d')),
                ('phoneNumber', models.CharField(blank=True, max_length=20, verbose_name='\u8054\u7cfb\u7535\u8bdd')),
                ('address', models.CharField(blank=True, max_length=20, verbose_name='\u8054\u7cfb\u5730\u5740')),
                ('receiveCode', models.CharField(max_length=20, verbose_name='\u4ea4\u8d27\u5730\u7f16\u7801')),
            ],
        ),
        migrations.CreateModel(
            name='SendClient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='\u59d3\u540d')),
                ('phoneNumber', models.CharField(blank=True, max_length=20, verbose_name='\u8054\u7cfb\u7535\u8bdd')),
                ('address', models.CharField(blank=True, max_length=20, verbose_name='\u8054\u7cfb\u5730\u5740')),
                ('sendCode', models.CharField(max_length=20, verbose_name='\u51fa\u8d27\u5730\u5b8c\u6574\u7801')),
            ],
        ),
    ]
